# Generated by Django 5.2.7 on 2025-02-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0008_alter_post_options_alter_tag_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webmention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.URLField()),
                ("target", models.URLField()),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("mention", "Mention"),
                            ("reply", "Reply"),
                            ("repost", "Repost"),
                            ("like", "Like"),
                        ],
                        default="mention",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.TextField(blank=True)),
                (
                    "target_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.post",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
