# Generated by Django 5.2.7 on 2026-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmention',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('timed_out', 'Timed out')], default='pending', max_length=16),
        ),
    ]
