# Generated by Django 5.2.12 on 2026-03-26 22:30

import re
import secrets
from urllib.parse import urlparse, urlunparse

from django.db import migrations, models


TOKEN_RE = re.compile(r"\w+", re.UNICODE)


def normalize_url(value: str) -> str:
    value = (value or "").strip()
    if not value:
        return ""
    parsed = urlparse(value)
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc:
        return ""
    path = parsed.path or "/"
    return urlunparse(
        (
            parsed.scheme.lower(),
            parsed.netloc.lower(),
            path,
            parsed.params,
            parsed.query,
            "",
        )
    )


def ensure_string_list(value) -> list[str]:
    if value in (None, ""):
        return []
    if isinstance(value, (list, tuple, set)):
        items = value
    else:
        items = [value]
    result = []
    for item in items:
        if isinstance(item, str):
            item = item.strip()
            if item:
                result.append(item)
    return result


def normalize_category(value: str) -> str:
    return " ".join((value or "").split()).strip().lower()


def extract_content_text(data: dict) -> str:
    content = data.get("content")
    if isinstance(content, dict):
        text = content.get("text")
        if isinstance(text, str) and text.strip():
            return text
        html = content.get("html")
        if isinstance(html, str):
            return html
    if isinstance(content, str):
        return content
    return ""


def tokenize_text(value: str) -> list[str]:
    seen = set()
    tokens = []
    for token in TOKEN_RE.findall((value or "").lower()):
        if token and token not in seen:
            seen.add(token)
            tokens.append(token)
    return tokens


def normalize_entry_data(data, uid: str, subscription_url: str = "") -> tuple[dict, dict]:
    payload = data.copy() if isinstance(data, dict) else {}
    internal_uid = payload.pop("_uid", "") or payload.get("uid") or uid
    payload["uid"] = str(internal_uid or uid)

    for prop in (
        "audio",
        "bookmark-of",
        "category",
        "in-reply-to",
        "like-of",
        "listen-of",
        "photo",
        "read-of",
        "repost-of",
        "syndication",
        "video",
        "watch-of",
    ):
        values = ensure_string_list(payload.get(prop))
        if values:
            payload[prop] = values
        elif prop in payload:
            payload.pop(prop, None)

    author_url = ""
    author = payload.get("author")
    if isinstance(author, dict):
        normalized_author = author.copy()
        normalized_author_url = normalize_url(author.get("url", "") or "")
        if normalized_author_url:
            normalized_author["url"] = normalized_author_url
            author_url = normalized_author_url
        payload["author"] = normalized_author

    source_url = normalize_url(subscription_url)
    if not source_url:
        source = payload.get("_source")
        if isinstance(source, dict):
            source_url = normalize_url(source.get("url", "") or "")

    search_text = " ".join(
        filter(
            None,
            [
                payload.get("name", "") if isinstance(payload.get("name"), str) else "",
                payload.get("summary", "") if isinstance(payload.get("summary"), str) else "",
                extract_content_text(payload),
            ],
        )
    )
    categories = [normalize_category(value) for value in ensure_string_list(payload.get("category"))]
    categories = [value for value in categories if value]
    metadata = {
        "author_url": author_url,
        "source_url": source_url,
        "kind_like": bool(ensure_string_list(payload.get("like-of"))),
        "kind_repost": bool(ensure_string_list(payload.get("repost-of"))),
        "kind_bookmark": bool(ensure_string_list(payload.get("bookmark-of"))),
        "kind_reply": bool(ensure_string_list(payload.get("in-reply-to"))),
        "kind_checkin": isinstance(payload.get("checkin"), dict),
        "kind_photo": bool(ensure_string_list(payload.get("photo"))),
        "kind_video": bool(ensure_string_list(payload.get("video"))),
        "kind_audio": bool(ensure_string_list(payload.get("audio"))),
        "tokens": tokenize_text(search_text),
        "categories": categories,
    }
    return payload, metadata


def forward(apps, schema_editor):
    Channel = apps.get_model("microsub", "Channel")
    Subscription = apps.get_model("microsub", "Subscription")
    Entry = apps.get_model("microsub", "Entry")
    EntrySearchToken = apps.get_model("microsub", "EntrySearchToken")
    EntryCategory = apps.get_model("microsub", "EntryCategory")

    notifications, _ = Channel.objects.get_or_create(
        uid="notifications",
        defaults={"name": "Notifications", "order": 0},
    )
    home, home_created = Channel.objects.get_or_create(
        uid="home",
        defaults={"name": "Home", "order": 1},
    )

    ordered = list(Channel.objects.order_by("order", "id"))
    reordered = [channel for channel in ordered if channel.uid not in {"notifications", "home"}]
    final_channels = [notifications, home] + reordered
    for index, channel in enumerate(final_channels):
        if channel.order != index:
            channel.order = index
            channel.save(update_fields=["order"])

    for subscription in Subscription.objects.all():
        changed = []
        if not subscription.websub_callback_token:
            subscription.websub_callback_token = secrets.token_hex(16)
            changed.append("websub_callback_token")
        if subscription.websub_hub and subscription.websub_subscribed_at:
            subscription.websub_subscribed_at = None
            changed.append("websub_subscribed_at")
        if changed:
            subscription.save(update_fields=changed)

    EntrySearchToken.objects.all().delete()
    EntryCategory.objects.all().delete()

    BATCH_SIZE = 500
    token_rows = []
    category_rows = []
    token_model = EntrySearchToken
    category_model = EntryCategory
    for entry in Entry.objects.select_related("subscription").all().iterator(chunk_size=BATCH_SIZE):
        payload, metadata = normalize_entry_data(
            entry.data,
            uid=entry.uid,
            subscription_url=entry.subscription.url if entry.subscription_id else "",
        )
        changed = []
        if entry.data != payload:
            entry.data = payload
            changed.append("data")
        for field_name in (
            "author_url",
            "source_url",
            "kind_like",
            "kind_repost",
            "kind_bookmark",
            "kind_reply",
            "kind_checkin",
            "kind_photo",
            "kind_video",
            "kind_audio",
        ):
            if getattr(entry, field_name) != metadata[field_name]:
                setattr(entry, field_name, metadata[field_name])
                changed.append(field_name)
        if changed:
            entry.save(update_fields=changed)
        token_rows.extend(token_model(entry_id=entry.id, token=token) for token in metadata["tokens"])
        category_rows.extend(category_model(entry_id=entry.id, value=value) for value in metadata["categories"])

        if len(token_rows) >= BATCH_SIZE:
            EntrySearchToken.objects.bulk_create(token_rows, ignore_conflicts=True)
            token_rows = []
        if len(category_rows) >= BATCH_SIZE:
            EntryCategory.objects.bulk_create(category_rows, ignore_conflicts=True)
            category_rows = []

    if token_rows:
        EntrySearchToken.objects.bulk_create(token_rows, ignore_conflicts=True)
    if category_rows:
        EntryCategory.objects.bulk_create(category_rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("microsub", "0004_fix_null_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="websub_callback_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="subscription",
            name="websub_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="source_url",
            field=models.URLField(blank=True, db_index=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_audio",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_bookmark",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_checkin",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_like",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_photo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_reply",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_repost",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="kind_video",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="EntrySearchToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(db_index=True, max_length=100)),
                ("entry", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="search_tokens", to="microsub.entry")),
            ],
        ),
        migrations.CreateModel(
            name="EntryCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(db_index=True, max_length=255)),
                ("entry", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="search_categories", to="microsub.entry")),
            ],
        ),
        migrations.AddConstraint(
            model_name="entrysearchtoken",
            constraint=models.UniqueConstraint(fields=("entry", "token"), name="microsub_entrysearchtoken_unique"),
        ),
        migrations.AddConstraint(
            model_name="entrycategory",
            constraint=models.UniqueConstraint(fields=("entry", "value"), name="microsub_entrycategory_unique"),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
