# Generated by hand to add OAuth credentials for syndication targets.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_elsewhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="mastodon_base_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mastodon_client_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mastodon_client_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mastodon_access_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mastodon_refresh_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mastodon_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_service",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_client_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_client_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_access_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_refresh_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_did",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bluesky_handle",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]

