# Generated by Django 5.2.7 on 2025-12-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_elsewhere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
