# Generated by Django 5.2.7 on 2025-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_siteconfiguration_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField()),
                ('to_path', models.CharField()),
                ('redirect_type', models.CharField(choices=[('temporary', '307 Temporary Redirect'), ('permanently', '301 Moved Permanently')], default='temporary', max_length=16)),
            ],
        ),
    ]
