# Generated by Django 5.2.7 on 2025-01-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteconfiguration_footer_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='robots_txt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
