# Generated by Django 5.2.7 on 2025-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteconfiguration_active_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='intro',
            field=models.TextField(default='', max_length=512),
        ),
    ]
