# Generated by Django 5.2.12 on 2026-03-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_seed_widgets_plugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='bridgy_publish_mastodon',
        ),
    ]
