# Generated by Django 5.2.12 on 2026-03-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_remove_bridgy_publish_mastodon"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="microsub_unfollow_removes_entries",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, unfollowing a feed removes its previously fetched entries from the channel instead of leaving them visible.",
                verbose_name="Microsub unfollow removes history",
            ),
        ),
    ]
