# Generated by Django 5.2.17 on 2026-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_siteconfiguration_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='activity_units',
            field=models.CharField(choices=[('imperial', 'Imperial (mi, ft)'), ('metric', 'Metric (km, m)')], default='imperial', help_text="Units used when generating activity post content summaries (e.g. from Strava imports). Structured mf2 properties always stay in the source's native units.", max_length=8, verbose_name='Activity units'),
        ),
    ]
