# Generated by Django 5.2.17 on 2026-10-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indieauth', '0003_personal_access_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('tool', models.CharField(blank=True, max_length=128)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('tool_error', 'Tool error'), ('error', 'Protocol error')], max_length=16)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('protocol_version', models.CharField(blank=True, max_length=32)),
                ('client_id', models.CharField(blank=True, max_length=2000)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indieauth.indieauthaccesstoken')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='mcp_server__created_c5db9c_idx')],
            },
        ),
    ]
