# Generated by Django 5.2.17 on 2026-09-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='synced_photo_ids',
            field=models.JSONField(blank=True, default=list, help_text="Strava photo unique_ids already downloaded, so update webhooks don't re-download them."),
        ),
    ]
