# Generated by Django 5.2.7 on 2025-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_alter_post_published_on_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
