# Generated by Django 5.2.7 on 2025-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('photo', 'Photo')], default='article', max_length=16),
        ),
    ]
