# Generated by Django 5.2.7 on 2025-11-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_on']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
