# Generated by Django 5.2.7 on 2025-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_reply_to',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like_of',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='repost_of',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(
                choices=[
                    ('article', 'Article'),
                    ('note', 'Note'),
                    ('photo', 'Photo'),
                    ('like', 'Like'),
                    ('repost', 'Repost'),
                    ('reply', 'Reply'),
                ],
                default='article',
                max_length=16,
            ),
        ),
    ]
