# Generated by Django 5.2.7 on 2025-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_in_reply_to_post_like_of_post_repost_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mf2',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
