# Generated by Django 5.2.7 on 2026-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_activityflyover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('photo', 'Photo'), ('activity', 'Activity'), ('like', 'Like'), ('repost', 'Repost'), ('reply', 'Reply')], default='article', max_length=16),
        ),
    ]
