# Generated by Django 5.2.17 on 2026-10-01 21:18

from django.db import migrations, models
from django.db.models import F
from django.utils import timezone


def backfill_went_live_at(apps, schema_editor):
    # Posts whose time has already passed have had their side effects sent at
    # save time; mark them so publish_due_posts doesn't send them again.
    Post = apps.get_model("blog", "Post")
    Post.objects.filter(published_on__lte=timezone.now()).update(went_live_at=F("published_on"))


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_mastodon_syndicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='went_live_at',
            field=models.DateTimeField(blank=True, help_text="When go-live side effects (webmentions, syndication) were queued. Null on drafts and scheduled posts that haven't reached their time.", null=True),
        ),
        migrations.RunPython(backfill_went_live_at, migrations.RunPython.noop),
    ]
