# Generated by Django 5.2.17 on 2026-10-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_went_live_at'),
        ('indieauth', '0002_indieauthrequestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('status', 'Status change'), ('delete', 'Delete'), ('undelete', 'Undelete'), ('revert', 'Revert')], max_length=16)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('actor_source', models.CharField(max_length=16)),
                ('client_id', models.CharField(blank=True, max_length=2000)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.post')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indieauth.indieauthaccesstoken')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
