# Generated by Django 5.2.17 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0002_indieauthrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='indieauthaccesstoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indieauthaccesstoken',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='indieauthaccesstoken',
            name='client_id',
            field=models.CharField(max_length=2000),
        ),
    ]
