# Generated by Django 5.2.17 on 2026-10-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0003_personal_access_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='indieauthaccesstoken',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='indieauthauthorizationcode',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='indieauthconsent',
            name='granted_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='IndieAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='indieauth.indieauthaccesstoken')),
            ],
        ),
    ]
