from django.urls import path

from . import views

app_name = "site_admin"

urlpatterns = [
    path("login/", views.SiteAdminLoginView.as_view(), name="login"),
    path("logout/", views.SiteAdminLogoutView.as_view(), name="logout"),
    path("bar/", views.admin_bar, name="admin_bar"),
    path("", views.dashboard, name="dashboard"),
    path("interactions/", views.interactions, name="interactions"),
    path("analytics/", views.analytics_dashboard, name="analytics_dashboard"),
    path("analytics/user-agents/", views.analytics_user_agents, name="analytics_user_agents"),
    path(
        "analytics/bot-detection/",
        views.analytics_bot_detection,
        name="analytics_bot_detection",
    ),
    path(
        "analytics/ignored-user-agents/",
        views.analytics_ignored_user_agents,
        name="analytics_ignored_user_agents",
    ),
    path(
        "analytics/mark-false-positive-user-agent/",
        views.analytics_mark_false_positive_user_agent,
        name="analytics_mark_false_positive_user_agent",
    ),
    path(
        "analytics/unmark-false-positive-user-agent/",
        views.analytics_unmark_false_positive_user_agent,
        name="analytics_unmark_false_positive_user_agent",
    ),
    path(
        "analytics/ignored-user-agents/export/",
        views.analytics_ignored_user_agents_export,
        name="analytics_ignored_user_agents_export",
    ),
    path(
        "analytics/errors/user-agents/",
        views.analytics_errors_by_user_agent,
        name="analytics_errors_by_user_agent",
    ),
    path(
        "analytics/ignore-user-agent/",
        views.analytics_ignore_user_agent,
        name="analytics_ignore_user_agent",
    ),
    path(
        "analytics/ignore-user-agents/",
        views.analytics_ignore_user_agents_bulk,
        name="analytics_ignore_user_agents_bulk",
    ),
    path(
        "analytics/unignore-user-agent/",
        views.analytics_unignore_user_agent,
        name="analytics_unignore_user_agent",
    ),
    path(
        "analytics/delete-error/",
        views.analytics_delete_error,
        name="analytics_delete_error",
    ),
    path("analytics/redirects/", views.redirect_list, name="redirect_list"),
    path("analytics/redirects/new/", views.redirect_edit, name="redirect_create"),
    path(
        "analytics/redirects/<int:redirect_id>/",
        views.redirect_edit,
        name="redirect_edit",
    ),
    path(
        "analytics/redirects/<int:redirect_id>/delete/",
        views.redirect_delete,
        name="redirect_delete",
    ),
    path("settings/", views.site_settings, name="site_settings"),
    path("settings/themes/", views.theme_settings, name="theme_settings"),
    path("settings/themes/git-refs/", views.theme_git_refs, name="theme_git_refs"),
    path(
        "settings/themes/<slug:slug>/edit/",
        views.theme_file_edit,
        name="theme_file_edit",
    ),
    path(
        "settings/themes/installs/<slug:slug>/",
        views.theme_install_detail,
        name="theme_install_detail",
    ),
    path("profile/", views.profile_edit, name="profile_edit"),
    path("profile/urls/<int:url_id>/delete/", views.profile_url_delete, name="profile_url_delete"),
    path("profile/emails/<int:email_id>/delete/", views.profile_email_delete, name="profile_email_delete"),
    path("profile/upload-photo/", views.profile_upload_photo, name="profile_upload_photo"),
    path("profile/delete-photo/", views.profile_delete_photo, name="profile_delete_photo"),
    path("settings/menus/", views.menu_list, name="menu_list"),
    path("settings/menus/new/", views.menu_edit, name="menu_create"),
    path("settings/menus/<int:menu_id>/", views.menu_edit, name="menu_edit"),
    path(
        "settings/menus/items/<int:item_id>/delete/",
        views.menu_item_delete,
        name="menu_item_delete",
    ),
    path("settings/errors/", views.error_log_list, name="error_log_list"),
    path("settings/errors/<int:log_id>/", views.error_log_detail, name="error_log_detail"),
    path("settings/tasks/", views.task_log_list, name="task_log_list"),
    path("settings/tasks/<str:task_id>/", views.task_log_detail, name="task_log_detail"),
    path("settings/indieauth/", views.indieauth_settings, name="indieauth_settings"),
    path(
        "settings/indieauth/clients/new/",
        views.indieauth_client_create,
        name="indieauth_client_create",
    ),
    path(
        "settings/indieauth/clients/<int:client_pk>/",
        views.indieauth_client_detail,
        name="indieauth_client_detail",
    ),
    path(
        "settings/indieauth/clients/<int:client_pk>/edit/",
        views.indieauth_client_edit,
        name="indieauth_client_edit",
    ),
    path("pages/", views.page_list, name="page_list"),
    path("pages/new/", views.page_edit, name="page_create"),
    path("pages/<slug:slug>/delete/", views.page_delete, name="page_delete"),
    path("pages/<slug:slug>/", views.page_edit, name="page_edit"),
    path("posts/upload-photo/", views.upload_post_photo, name="post_upload_photo"),
    path("posts/delete-photo/", views.delete_post_photo, name="post_delete_photo"),
    path("posts/nearby-places/", views.nearby_checkin_places, name="nearby_checkin_places"),
    path("posts/", views.post_list, name="post_list"),
    path("posts/new/", views.post_edit, name="post_create"),
    path("posts/<slug:slug>/delete/", views.post_delete, name="post_delete"),
    path(
        "posts/<slug:slug>/delete-permanent/",
        views.post_permanent_delete,
        name="post_permanent_delete",
    ),
    path("posts/<slug:slug>/", views.post_edit, name="post_edit"),
    path("comments/", views.comment_list, name="comment_list"),
    path("comments/<int:comment_id>/", views.comment_detail, name="comment_detail"),
    path("comments/<int:comment_id>/approve/", views.comment_approve, name="comment_approve"),
    path("comments/<int:comment_id>/spam/", views.comment_mark_spam, name="comment_mark_spam"),
    path("comments/<int:comment_id>/delete/", views.comment_delete, name="comment_delete"),
    path("webmentions/", views.webmention_list, name="webmention_list"),
    path("micropub/errors/", views.micropub_error_list, name="micropub_error_list"),
    path(
        "micropub/errors/<int:log_id>/",
        views.micropub_error_detail,
        name="micropub_error_detail",
    ),
    path("indieauth/errors/", views.indieauth_error_list, name="indieauth_error_list"),
    path(
        "indieauth/errors/<int:log_id>/",
        views.indieauth_error_detail,
        name="indieauth_error_detail",
    ),
    path("webmentions/new/", views.webmention_create, name="webmention_create"),
    path("webmentions/<int:mention_id>/", views.webmention_detail, name="webmention_detail"),
    path(
        "webmentions/<int:mention_id>/resend/",
        views.webmention_resend,
        name="webmention_resend",
    ),
    path(
        "webmentions/<int:mention_id>/approve/",
        views.webmention_approve,
        name="webmention_approve",
    ),
    path(
        "webmentions/<int:mention_id>/reject/",
        views.webmention_reject,
        name="webmention_reject",
    ),
    path(
        "webmentions/<int:mention_id>/delete/",
        views.webmention_delete,
        name="webmention_delete",
    ),
    path("files/", views.file_list, name="file_list"),
    path("files/new/", views.file_create, name="file_create"),
    path("files/<int:file_id>/delete/", views.file_delete, name="file_delete"),
    path("files/<int:file_id>/", views.file_edit, name="file_edit"),
    # Plugins (under settings)
    path("settings/plugins/", views.plugin_list, name="plugin_list"),
    path("settings/plugins/install/", views.plugin_install, name="plugin_install"),
    path("settings/plugins/restart-status/", views.plugin_restart_status, name="plugin_restart_status"),
    path("settings/plugins/<slug:slug>/update/", views.plugin_update, name="plugin_update"),
    path("settings/plugins/<slug:slug>/remove/", views.plugin_remove, name="plugin_remove"),
    # Widgets (plugin detail page, under settings/plugins)
    path("settings/plugins/widgets/", views.widget_list, name="widget_list"),
    path("settings/plugins/widgets/add/", views.widget_add, name="widget_add"),
    path("settings/plugins/widgets/reorder/", views.widget_reorder, name="widget_reorder"),
    path("settings/plugins/widgets/<int:pk>/edit/", views.widget_edit, name="widget_edit"),
    path("settings/plugins/widgets/<int:pk>/delete/", views.widget_delete, name="widget_delete"),
    # Microsub
    path("microsub/", views.microsub_channel_list, name="microsub_channel_list"),
    path("microsub/channels/new/", views.microsub_channel_create, name="microsub_channel_create"),
    path("microsub/channels/reorder/", views.microsub_channel_reorder, name="microsub_channel_reorder"),
    path("microsub/channels/<slug:uid>/", views.microsub_channel_detail, name="microsub_channel_detail"),
    path("microsub/channels/<slug:uid>/edit/", views.microsub_channel_edit, name="microsub_channel_edit"),
    path("microsub/channels/<slug:uid>/delete/", views.microsub_channel_delete, name="microsub_channel_delete"),
    path("microsub/channels/<slug:uid>/mark-read/", views.microsub_channel_mark_read, name="microsub_channel_mark_read"),
    path("microsub/channels/<slug:uid>/feeds/add/", views.microsub_feed_add, name="microsub_feed_add"),
    path("microsub/channels/<slug:uid>/feeds/<int:feed_id>/remove/", views.microsub_feed_remove, name="microsub_feed_remove"),
    path("microsub/import/", views.microsub_import_opml, name="microsub_import_opml"),
    # Mastodon
    path("mastodon/", views.mastodon_settings, name="mastodon_settings"),
    path("mastodon/disconnect/", views.mastodon_disconnect, name="mastodon_disconnect"),
    path("mastodon/sync/", views.mastodon_manual_sync, name="mastodon_manual_sync"),
]
