# Generated by Django 5.2.7 on 2025-10-27 15:48

import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('doc', 'Document'), ('video', 'Video')], default='image', max_length=16)),
                ('file', models.FileField(upload_to=files.models.upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='files.file')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
