# Generated by Django 5.2.7 on 2026-03-26 05:55
#
# NOTE: This migration changes client_secret and access_token from plain CharField
# to EncryptedCharField. Any existing plaintext values in those columns will become
# unreadable after this migration runs — the application will treat them as corrupt
# encrypted data. If you have an existing connected Mastodon account, disconnect it
# before deploying and reconnect afterwards.
#
# Requires FIELD_ENCRYPTION_KEY to be set in the environment (a Fernet key).
# Generate one with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

import encrypted_model_fields.fields
from django.db import migrations


def _check_no_existing_credentials(apps, schema_editor):
    """
    Abort the migration if any Mastodon credentials are already stored.

    Converting existing plaintext values to EncryptedCharField will make them
    unreadable.  Operators must disconnect the Mastodon account first, then
    reconnect after the migration runs.
    """
    MastodonAccount = apps.get_model("mastodon_integration", "MastodonAccount")
    MastodonApp = apps.get_model("mastodon_integration", "MastodonApp")
    if MastodonAccount.objects.exists() or MastodonApp.objects.filter(client_secret__gt="").exists():
        raise SystemExit(
            "\n"
            "ERROR: mastodon_integration migration 0002 cannot run while Mastodon\n"
            "credentials exist in the database.  Existing plaintext values would\n"
            "become unreadable after field encryption is applied.\n"
            "\n"
            "Steps to resolve:\n"
            "  1. Go to /admin/mastodon/ and click 'Disconnect'.\n"
            "  2. Re-run this migration.\n"
            "  3. Reconnect your Mastodon account.\n"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mastodon_integration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_check_no_existing_credentials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mastodonaccount',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='mastodonapp',
            name='client_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
